# -*- coding: utf-8 -*-
"""Fraud_detection_anomaly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YA2Ub4Hb72RHoZMQn1j_7m9CzJOeu7L3

Import libraries
"""

# Importing Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier, IsolationForest

data = pd.read_csv("transaction_anomalies_dataset.csv")
data.head()

"""Looking for null values in dataset"""

data.isnull().sum()

# Dataset shape
data.shape

# Column names and data types
data.info()

"""Dataset Shape & Structure

Histogram: Overall Distribution of Transaction Amount
"""

plt.figure()
plt.hist(data["Transaction_Amount"], bins=50)
plt.title("Distribution of Transaction Amounts")
plt.xlabel("Transaction Amount")
plt.ylabel("Frequency")
plt.show()

"""Check For The Account Types"""

data["Account_Type"].value_counts()

"""Transaction Amount by Account Type (Boxplot)"""

plt.figure()
data.boxplot(column="Transaction_Amount", by="Account_Type")
plt.title("Transaction Amount Distribution by Account Type")
plt.xlabel("Account Type")
plt.ylabel("Transaction Amount")
plt.show()

"""The histogram shows that most transaction amounts are concentrated within a narrow mid-range, representing typical customer behavior, while a small number of very high-value transactions appear far from the main cluster. This right-skewed distribution indicates the presence of potential outliers and justifies the use of anomaly detection techniques. The observed spread of values also highlights the importance of feature scaling during preprocessing

```
# This is formatted as code
```

Time Since Last Transaction vs Transaction Amount
"""

# x and y
x = data['Time_Since_Last_Transaction']
y = data['Transaction_Amount']

# Plotting a scatter plot
plt.scatter(x, y)

# The Trend line
m, b = np.polyfit(x, y, 1)
plt.plot(x, m*x + b)

# Labeling
plt.xlabel('Time Since Last Transaction')
plt.ylabel('Transaction Amount')
plt.title('Time Since Last Transaction vs Transaction Amount with Trend Line')

plt.show()

# Select numeric columns
featurescale = [
    'Transaction_Amount',
    'Average_Transaction_Amount',
    'Frequency_of_Transactions',
    'Time_Since_Last_Transaction',
    'Age',
    'Income',
    'Transaction_Volume'
]

X = data[featurescale]

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled[:5]

"""No missing values detected → skipping imputation step"""

from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(
    X_scaled,
    test_size=0.2,
    random_state=42
)
print("Total samples:", X_scaled.shape)
print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

# Since the dataset does not contain labeled fraud instances,
# the problem was treated as an unsupervised anomaly detection task.
# A random 80:20 train–test split was performed to learn normal transaction
# patterns from the training data and evaluate anomaly detection performance on unseen data.

# Train Isolation Forest
iso_forest = IsolationForest(
    n_estimators=100,
    contamination=0.05,   # assume ~5% anomalies
    random_state=42
)

iso_forest.fit(X_scaled)

# Predict anomalies
data['IF_Anomaly'] = iso_forest.predict(X_scaled)

# Convert: -1 = anomaly, 1 = normal
data['IF_Anomaly'] = data['IF_Anomaly'].map({1: 0, -1: 1})

# Count anomalies
data['IF_Anomaly'].value_counts()

# Calculate the number of anomalies
num_anomalies = data['IF_Anomaly'].sum()

# Calculate the total number of instances in the dataset
total_instances = data.shape[0]

# Calculate the ratio of anomalies
anomaly_ratio = num_anomalies / total_instances
print(anomaly_ratio)

# Isolation forest
relevant_features = ['Transaction_Amount', 'Average_Transaction_Amount', 'Frequency_of_Transactions']

# Split data into features (X) and target variable (y)
X = data[relevant_features]
y = data['IF_Anomaly']

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Train the Isolation Forest model
model = IsolationForest(contamination = 0.02, random_state = 42)
model.fit(X_train)

# Predict anomalies on the test set
y_pred = model.predict(X_test)

# Convert predictions to binary values (0: normal, 1: anomaly)
y_pred_binary = [1 if pred == -1 else 0 for pred in y_pred]

# Evaluate the model's performance
report = classification_report(y_test, y_pred_binary, target_names=['Normal', 'Anomaly'])
print(report)

data['Anomaly_Score'] = iso_forest.decision_function(X_scaled)

data.sort_values('Anomaly_Score').head(10)

plt.figure(figsize=(8,5))
plt.hist(data['Anomaly_Score'], bins=30)
plt.xlabel("Anomaly Score")
plt.ylabel("Frequency")
plt.title("Isolation Forest Anomaly Score Distribution")
plt.show()

"""Auto encoder model"""

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_scaled.shape[1]

input_layer = Input(shape=(input_dim,))

encoder = Dense(16, activation="relu")(input_layer)
encoder = Dense(8, activation="relu")(encoder)

decoder = Dense(16, activation="relu")(encoder)
decoder = Dense(input_dim, activation="linear")(decoder)

autoencoder = Model(inputs=input_layer, outputs=decoder)

autoencoder.compile(optimizer='adam',loss='mse')

history = autoencoder.fit(
    X_scaled,
    X_scaled,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    shuffle=True,
    verbose=1
)

reconstructions = autoencoder.predict(X_scaled)
reconstruction_error = np.mean(
    np.square(X_scaled - reconstructions), axis=1
)

threshold = np.percentile(reconstruction_error, 95)

data['AE_Anomaly'] = reconstruction_error > threshold
data['AE_Anomaly'] = data['AE_Anomaly'].map({True: 1, False: 0})

data['AE_Anomaly'].value_counts()

"""An autoencoder is a neural network trained to reconstruct normal data patterns. Transactions with high reconstruction error are considered anomalous and flagged as potential fraud."""

# Assuming X is your feature data
model = IsolationForest(contamination=0.05, random_state=42)
model.fit(X)

# Predict anomalies: -1 means anomaly, 1 means normal
predictions = model.predict(X)

# Convert to 0 (normal) and 1 (anomaly)
IF_Anomaly = (predictions == -1).astype(int)

plt.hist(reconstruction_error, bins=30)
plt.axvline(threshold, color='red')
plt.title("Autoencoder Reconstruction Error")
plt.show()

print(f'Number of anomalies detected: {np.sum(IF_Anomaly)}')

print(data.columns)

from sklearn.ensemble import IsolationForest
import numpy as np
import matplotlib.pyplot as plt

# Assuming X is your feature matrix
iso_model = IsolationForest(contamination=0.05, random_state=42)
iso_model.fit(X)

# Anomaly scores (the lower, the more normal; the higher, the more anomalous)
anomaly_scores_IF = -iso_model.score_samples(X)  # negate for intuitive "high = anomaly"

# Basic statistics
mean_IF = np.mean(anomaly_scores_IF)
std_IF = np.std(anomaly_scores_IF)
print("Isolation Forest - Mean Score:", mean_IF)
print("Isolation Forest - Std Dev:", std_IF)

# Histogram
plt.hist(anomaly_scores_IF, bins=30, color='skyblue', edgecolor='black')
plt.title('Isolation Forest: Distribution of Anomaly Scores')
plt.xlabel('Anomaly Score')
plt.ylabel('Frequency')
plt.show()

anomaly_threshold_IF = mean_IF + 2 * std_IF
data['IF_Anomaly'] = anomaly_scores_IF > anomaly_threshold_IF
print("Number of anomalies detected:", data['IF_Anomaly'].sum())

plt.hist(anomaly_scores_IF, bins=30, color='skyblue', edgecolor='black')
plt.axvline(anomaly_threshold_IF, color='red', linestyle='--', label='Anomaly Threshold')
plt.title('Isolation Forest: Anomaly Score Distribution')
plt.xlabel('Anomaly Score')
plt.ylabel('Frequency')
plt.legend()
plt.show()

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

# Simple Autoencoder
input_dim = X.shape[1]
input_layer = Input(shape=(input_dim,))
encoded = Dense(8, activation='relu')(input_layer)
decoded = Dense(input_dim, activation='sigmoid')(encoded)
autoencoder = Model(inputs=input_layer, outputs=decoded)
autoencoder.compile(optimizer='adam', loss='mse')

# Train autoencoder
autoencoder.fit(X, X, epochs=50, batch_size=32, shuffle=True, verbose=0)

# Reconstruction error
reconstructions = autoencoder.predict(X)
reconstruction_errors = np.mean(np.square(X - reconstructions), axis=1)

# Basic statistics
mean_AE = np.mean(reconstruction_errors)
std_AE = np.std(reconstruction_errors)
print("Autoencoder - Mean Reconstruction Error:", mean_AE)
print("Autoencoder - Std Dev:", std_AE)

# Histogram
plt.hist(reconstruction_errors, bins=30, color='salmon', edgecolor='black')
plt.title('Autoencoder: Distribution of Reconstruction Errors')
plt.xlabel('Reconstruction Error')
plt.ylabel('Frequency')
plt.show()

anomaly_threshold_AE = mean_AE + 2 * std_AE
data['AE_Anomaly'] = reconstruction_errors > anomaly_threshold_AE
print("Number of anomalies detected by Autoencoder:", data['AE_Anomaly'].sum())

plt.hist(reconstruction_errors, bins=30, color='salmon', edgecolor='black')
plt.axvline(anomaly_threshold_AE, color='red', linestyle='--', label='Anomaly Threshold')
plt.title('Autoencoder: Reconstruction Error Distribution')
plt.xlabel('Reconstruction Error')
plt.ylabel('Frequency')
plt.legend()
plt.show()